version: '2'

volumes:
  postgres_data_vol:
    external: false

services:

  postgres:
    image: postgres:9.6
    command: |-
      /bin/bash -c "
        echo \"$$POSTGRES_INITDB\" > /docker-entrypoint-initdb.d/commands.sh &&
        chmod +x /docker-entrypoint-initdb.d/commands.sh &&
        /docker-entrypoint.sh postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_INITDB: |
        sed -i -e 's/max_connections.*/max_connections = 5000/' /var/lib/postgresql/data/postgresql.conf
        sed -i -e 's/#log_min_duration_statement = .*/log_min_duration_statement = 0/' /var/lib/postgresql/data/postgresql.conf
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data/
    stdin_open: true
    tty: true    
